### ISSUE TITLE
convert icon outlines to paths

### ISSUE THREAD

**Issue by steveharoz** [steveharoz/open-access-vis#20]

**Comment by yelper** [comment]
Once we get DOIs, could use a service like [doi2bib](http://www.doi2bib.org/#/doi) or [citation-js](https://www.npmjs.com/package/citation-js).

**Comment by steveharoz** [comment]
Hi @yelper. In the desktop version of the site, it generates a citation in IEEE and bibtex formats. What would those libraries add?

**Comment by yelper** [comment]
It would create a "full" bibtex citation from metadata on IEEE's servers (adding page, issue, and volume info, you wouldn't have to scrape it yourself), just given the DOI of each paper.  It would be a one-time thing once the issue is online.
