### ISSUE TITLE
A supplementary material website of our paper is available at http://graphvis.net/wgl

### ISSUE THREAD

**Issue by kwonoh** [steveharoz/open-access-vis#23]
Session: InfoVis Graphs and Paths
THURSDAY, OCTOBER 5
4:15pm-5:55pm
Room: 301-D

Paper: What Would a Graph Look Like in This Layout? A Machine Learning Approach to Large Graph Visualization
Authors: Oh-Hyun Kwon, Tarik Crnovrsanin, Kwan-Liu Ma

A supplementary material website of our paper is available at http://graphvis.net/wgl

**Comment by steveharoz** [comment]
@kwonoh Added. If you post the two results in a machine readable format like CSV, Excel file, or JSON, I can give you a "data" badge too.

**Comment by kwonoh** [comment]
@steveharoz  BTW, the paper title on your website is the previous one. 
The new title is: What Would a Graph Look Like in This Layout? A **Machine Learning** Approach to Large Graph Visualization

**Comment by steveharoz** [comment]
Fixed :)

**Comment by kwonoh** [comment]
@steveharoz Thank you 👍
