### ISSUE TITLE
Paper URL (Missing Data)

### ISSUE THREAD

**Issue by arjun010** [steveharoz/open-access-vis#25]
Paper: Orko: Facilitating Multimodal Interaction for Visual Network Exploration and Analysis
Arjun Srinivasan, John Stasko
5:15-5:35 PM  Thursday  301-D

URL: http://arjun010.github.io/static/papers/orko-infovis-17.pdf
Teaser: http://arjun010.github.io/static/images/orko_teaser.jpg

**Comment by steveharoz** [comment]
Thanks. It's posted
