### ISSUE TITLE
Anchoring Effect with Visual Analytics GitHub and Materials

### ISSUE THREAD

**Issue by wesslen** [steveharoz/open-access-vis#29]
Paper: "The Anchoring Effect in Decision-Making with Visual Analytics" VAST 2017, Theory and Analysis Process on Thursday

Pdf: https://github.com/wesslen/vast2017-anchoringeffect/raw/master/anchorbias.pdf
GitHub: https://github.com/wesslen/vast2017-anchoringeffect
- includes code, raw data (csv, json), abstract and explanations.
Thumbnail: https://github.com/wesslen/vast2017-anchoringeffect/raw/master/img/anchoring_isaac.png

Thanks for organizing the materials! 

Let me know if you have any questions.

**Comment by steveharoz** [comment]
Thanks for the info! Is the PDF available anywhere else? Github isn't a good host for PDFs because it requires either a download or an image-based viewer that doesn't let you copy text.

If you don't have another site, I recommend http://osf.io

**Comment by wesslen** [comment]
Yes. Would a GitHub Page work?
https://wesslen.github.io/assets/documents/papers/anchorbias.pdf

If not, I could look into http://osf.io

**Comment by steveharoz** [comment]
That works. Thanks. I'll update the page.
