### ISSUE TITLE
MyBrush paper

### ISSUE THREAD

**Issue by charlesperin** [steveharoz/open-access-vis#30]
Thanks Steve, that's an amazing initiative. And I see the community is engaged and contributing, so well done! I'm trying to not be ranked first in your chart-of-shame anymore... So, here is the info for a first paper:

Title:
MyBrush: Brushing and Linking with Personal Agency

Abstract:
We extend the popular brushing and linking technique by incorporating personal agency in the interaction. We first map existing research related to brushing and linking into a design space that deconstructs the interaction technique into three components: source (what is being brushed), link (the expression of relationship between source and target), and target (what is revealed as related to the source). Based on the generative power of this design space, we present MyBrush, a unified interface that offers personal agency over brushing and linking by giving people the flexibility to configure the source, link, and target of multiple brushes. The results of three focus groups demonstrate that people with different backgrounds leveraged personal agency in different ways, including performing complex tasks and showing links explicitly. We reflect on these results, paving the way for future research on the role of personal agency in information visualization.

thumbnail:
![mybrush-thumbnail](https://user-images.githubusercontent.com/6230546/29831405-f823dd0e-8cdc-11e7-9119-eb5ad32afd67.png)

Other columns (note that everything is available on the project page: http://innovis.cpsc.ucalgary.ca/supplemental/MyBrush/):
AuthorPDF
http://innovis.cpsc.ucalgary.ca/supplemental/MyBrush/2018_VIS_mybrush.pdf

Abstract
We extend the popular brushing and linking technique by incorporating personal agency in the interaction. We map existing research related to brushing and linking into a design space that deconstructs the interaction technique into three components: source (what is being brushed), link (the expression of relationship between source and target), and target (what is revealed as related to the source). Using this design space, we created MyBrush, a unified interface that offers personal agency over brushing and linking by giving people the flexibility to configure the source, link, and target of multiple brushes. The results of three focus groups demonstrate that people with different backgrounds leveraged personal agency in different ways, including performing complex tasks and showing links explicitly. We reflect on these results, paving the way for future research on the role of personal agency in information visualization.

ExplanationPage
http://innovis.cpsc.ucalgary.ca/supplemental/MyBrush/

SourceMaterials
http://innovis.cpsc.ucalgary.ca/supplemental/MyBrush/

Video
https://www.youtube.com/watch?v=1iAtPhWEV9I

Cheers,
-Charles

**Comment by steveharoz** [comment]
Thanks for helping Charles! The data's up on OAVIS, and I'll update the blog post tonight. 

Also, given how many papers you have this year (congrats, by the way), if you posted all of them on an open access repository (osf.io, arxiv.org, etc.), you could become the author with the most reliably open access papers. The current leaders only have 2.

**Comment by charlesperin** [comment]
Yeah that's true (and thanks!), I've considered it but it requires a lot of talking and discussing with co-authors from different institutions. So it may happen at a point, and I'll update the links when it happens, but for now the priority is to have everything available somewhere.
