### ISSUE TITLE
Assessing the Graphical Perception of Time and Speed on 2D+Time Trajectories

### ISSUE THREAD

**Issue by charlesperin** [steveharoz/open-access-vis#31]
That's two!

Title:
Assessing the Graphical Perception of Time and Speed on 2D+Time Trajectories

Abstract:
We empirically evaluate the extent to which people perceive non-constant time and speed encoded on 2D paths. In our graphical perception study, we evaluate nine encodings from the literature for both straight and curved paths. Visualizing time and speed information is a challenge when the x and y axes already encode other data dimensions, for example when plotting a trip on a map. This is particularly true in disciplines such as time-geography and movement analytics that often require visualizing spatio-temporal trajectories. A common approach is to use 2D+time trajectories, which are 2D paths for which time is an additional dimension. However, there are currently no guidelines regarding how to represent time and speed on such paths. Our study results provide InfoVis designers with clear guidance regarding which encodings to use and which ones to avoid; in particular, we suggest using color value to encode speed and segment length to encode time whenever possible.

thumbnail:
![timevis_thumbnail-square](https://user-images.githubusercontent.com/6230546/29844324-d0e68942-8d06-11e7-8d78-b44e15112a48.png)

Again, everything is available on the project page: http://innovis.cpsc.ucalgary.ca/supplemental/2DTimeTrajectories/):

AuthorPDF
http://innovis.cpsc.ucalgary.ca/supplemental/2DTimeTrajectories/2018_VIS_assessing_graphical_perception.pdf

ExplanationPage
http://innovis.cpsc.ucalgary.ca/supplemental/2DTimeTrajectories/

Experiment Data
http://innovis.cpsc.ucalgary.ca/supplemental/2DTimeTrajectories/#study

Video
https://www.youtube.com/watch?v=OGccwtpg8JI

-Charles

**Comment by steveharoz** [comment]
it's posted

FYI: For the explanatory page, I'm looking for more that what's already on OAVIS. It should be a laymen explanation and/or a demo.  Here's a great example: http://www.aviz.fr/~bbach/timecurves/
