### ISSUE TITLE
GapChart paper

### ISSUE THREAD

**Issue by charlesperin** [steveharoz/open-access-vis#34]
Title:
Using Gap Charts to Visualize the Temporal Evolution of Ranks and Scores

Thumbnail:
![gapchart_thumbnail](https://user-images.githubusercontent.com/6230546/29869788-58231a7c-8d7c-11e7-8737-f718c9100718.png)

PDF:
http://charles.perin.free.fr/data/pub/gapchart.pdf

Abstract:
We present Gap Charts, a novel class of line charts designed for visualizing the evolution of rankings over time, with a particular focus on sports data. Gap Charts show entries, e. g., teams participating in a competition, that are ranked over time according to a performance metric like a growing number of points or a score. The main advantages of Gap Charts are that 1) tied entries never overlap—only changes in rank generate limited overlap between time-steps; and 2) gaps between entries show the magnitude of their score difference. We evaluate the effectiveness of Gap Charts for performing different types of tasks, and find that they outperform standard time-dependent ranking visualizations for tasks that involve identifying and understanding evolutions in both ranks and scores. Finally, we show that Gap Charts are a generic and scalable class of line charts by applying them to a variety of different datasets.

**Comment by steveharoz** [comment]
Is that the same as "GapChart: a Gap Strategy to Visualize the Temporal Evolution of both Ranks and Scores"?

**Comment by charlesperin** [comment]
Oh, interesting... Thanks for checking that, actually there is a mistake in the program. The paper should be called "Using Gap Charts to Visualize the Temporal Evolution of Ranks and Scores". That is also the title in the CG&A special issue, and the title on ieeexplore. I will contact them to fix that.

**Comment by steveharoz** [comment]
Made an issue, so I can track it - https://github.com/ieee-vgtc/ieeevis.org/issues/245

Is "Using..." the title you want to use?

**Comment by steveharoz** [comment]
Now consistent with IEEE
