### ISSUE TITLE
Update: HiPiler: Visual Exploration Of Large Genome Interaction Matrices With Interactive Small Multiples

### ISSUE THREAD

**Issue by flekschas** [steveharoz/open-access-vis#36]
Our paper is on bioRxiv since the submission deadline, including the revision:

DOI: 10.1101/123588
URL: http://www.biorxiv.org/content/early/2017/07/09/123588

Not sure what criteria is applied but I think bioRxiv is a _reliable open access repository_.

Also, all the data we used is publicly available too:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63525

(GEO is one of the two major data repositories for genomic data)

The config for loading this demo (and more) is open-source too:

https://gist.github.com/flekschas/8b0163f25fd4ffb067aaba2a595da447

PS: Thanks for pulling this list together!

**Comment by steveharoz** [comment]
Hi Fritz. HiPiler was one of the first I found and has been on OAVIS and marked as on a reliable open access repository from the beginning :)

Any of the following URLs are counted as reliable repositories:  osf.io, arxiv.org, **biorxiv.org**, psyarxiv.org, hal.inria.fr, hal.archives-ouvertes.fr, eprints.whiterose.ac.uk  (I need to make this more clear in the docs)

For data, I use the center for open science definition, which is the results of an experiment in the paper. I have, however, linked to the source code as materials.

**Comment by flekschas** [comment]
Cool thanks!
