### ISSUE TITLE
New paper: Understanding Hidden Memories of Recurrent Neural Networks

### ISSUE THREAD

**Issue by myaooo** [steveharoz/open-access-vis#39]
Dear Steve,

Thank you for your efforts for the good of the community! I really like the initiative of the "Open Access VIS". I have upload related materials to the OSF. The URLs are listed below:

ReviewVenue: VAST

PublicationVenue: VAST17

Title: Understanding Hidden Memories of Recurrent Neural Networks

Authors: Yao Ming, Shaozu CAO, Ruixiang Zhang, Zhen LI, Yuanzhe Chen, Yangqiu Song, Huamin Qu

AuthorPDF: https://mfr.osf.io/render?url=https://osf.io/f36tb/?action=download%26mode=render

ExplanationPage: http://www.myaooo.com/rnnvis

SourceMaterials: http://github.com/myaooo/rnnvis

Data: http://www.myaooo.com/rnnvis

Video: https://www.youtube.com/watch?v=0QFDNLdQ6_w

-----------
Not sure if the following information is useful:

Supplement Material: https://mfr.osf.io/render?url=https://osf.io/7grp8/?action=download%26mode=render

Teaser Image (400x300): https://mfr.osf.io/render?url=https://osf.io/zu2nh/?action=download%26mode=render

Again, thank you for your efforts!

Best,
Yao

**Comment by steveharoz** [comment]
Thanks Yao. The paper, image, video, and materials are added. I linked to the paper in a way that allows people to see the supplemental material next to it. However, the data category is for experiment results such as experiment subject responses or algorithmic run-time results. I'm not sure the data sets here fit into that.
