### ISSUE TITLE
Material for paper available

### ISSUE THREAD

**Issue by ebertini** [steveharoz/open-access-vis#41]
New URL for material and code and data:

1. A Workflow for Visual Diagnostics of Binary Classifiers using Instance-Level Explanations
2. Paper URL: https://arxiv.org/abs/1705.01968

GitHub page: https://github.com/nyuvis/explanation_explorer

Better thumbnail: 
<img width="200" alt="explainer" src="https://user-images.githubusercontent.com/2347619/30304536-ff4487be-973b-11e7-9c95-987b11dfbc6d.png">

Thanks!

**Comment by steveharoz** [comment]
Updated. The thumbnails sometimes need a couple hard page refreshes.
