### ISSUE TITLE
Taking Word Clouds Apart: An Empirical Investigation of the Design Space for Keyword Summaries

### ISSUE THREAD

**Issue by CristianFelix** [steveharoz/open-access-vis#43]
Hi Steve, thank you. 

I have a few changes to my paper. Could you update it?

Paper Title: Taking Word Clouds Apart: An Empirical Investigation of the Design Space for Keyword Summaries

First Author: Cristian Felix

Fix authors order to :Cristian Felix, Steven Franconeri, Enrico Bertini
Add Explanation Page: https://nyuvis.github.io/word-cloud/

Thank You

**Comment by steveharoz** [comment]
Hi Cristian. I'll update the author order shortly :)

I only add explanation pages that have more than what is already on OAVis (metadata, abstract, video, etc.). Feel free to check out some of the other papers on OAVis with explanation pages for ideas.
