### ISSUE TITLE
SkyLens: Visual Analysis of Skyline on Multi-dimensional Data

### ISSUE THREAD

**Issue by wdan** [steveharoz/open-access-vis#44]
Hi Steve,

This project is really great and thanks a lot for your contribution!

Our paper has some additional information and I'm wondering if you could help update it.

Paper Title: SkyLens: Visual Analysis of Skyline on Multi-dimensional Data
First Author: Xun Zhao

Information to be added:
Material link: zhaoxun.me/skylens/
Explanation link: http://vis.cse.ust.hk/skylens/

Thank you again!

Best,
Yanhong

**Comment by steveharoz** [comment]
Thanks Yanhong. I've added the demo. The site should update later today.

Could you host the reproducibility materials on a site like OSF or github? I don't like linking directly to ZIPs without a clear explanation of what people are downloading.
