### ISSUE TITLE
Request to update the list of open access papers for Vis 2018

### ISSUE THREAD

**Issue by johanna-b** [steveharoz/open-access-vis#59]
Hanspeter Pfister's papers at Vis 2018 are all publicly available here: https://vcg.seas.harvard.edu/
2 of them are currently listed as hidden.

**Comment by steveharoz** [comment]
Hi Johanna. Thanks for pointing that out. When I click the PDF links on the publications page, it pops open a new tab, and it asks me to save a file. Perhaps a setting needs to be adjusted on the server? If you're not sure how to fix the problem, posting the papers to an open access repository like osf.io/preprints, arxiv.org, or biorxiv.org will fix the issue.

**Comment by mbehrisch** [comment]
Hi Steve.

Thanks for compiling this great paper list! This is a great effort! We highly appreciate it!
The VCG group has the overall credo to make all publications **publicly** available in one way or the other. That is why I have to ask you to correct the two incorrect paywall mentionings.

1. Commercial Visual Analytics Systems-Advances in the Big Data Analytics Field
M. Behrisch, D. Streeb, F. Stoffel, D. Seebacher, B. Matejek, S. H. Weber, S. Mittelstaedt, H. Pfister, and D. Keim — IEEE Transactions on Visualization and Computer Graphics.
is available here: https://vcg.seas.harvard.edu/publications/commercial-visual-analytics-systems-advances-in-the-big-data-analytics-field/paper
and here: https://commercialtools.dbvis.de/assets/data/submission/CommercialTools_TVCG_Journal_FINAL.pdf

2. DXR: A Toolkit for Building Immersive Data Visualizations
Sicat R, Li J, Choi J, Cordeil M, Jeong W, Bach B, and Pfister H — IEEE Transactions on Visualization and Computer Graphics (Proceedings IEEE Information Visualization 2018).
is available here: https://vcg.seas.harvard.edu/publications/dxr-a-toolkit-for-building-immersive-data-visualizations/paper

Thanks,
Michael Behrisch

**Comment by steveharoz** [comment]
Thank you for the links Michael! And sorry for missing them previously. I've updated both (should be visible on oavis soon).

Just FYI: Something weird is going on with the vcg.seas.harvard.edu paper links. I can't view the PDFs in my browser unless I download them first. That's probably why they were missed in the first place.

**Comment by steveharoz** [comment]
Thumbnails should be updated later tonight. The graph on my blog is now updated to reflect the new data. Congrats and thanks to you and Hanspeter for having so many open papers!
