### ISSUE TITLE
Evaluating 'Graphical Perception' with CNNs

### ISSUE THREAD

**Issue by haehn** [steveharoz/open-access-vis#64]
Evaluating 'Graphical Perception' with CNNs is now on OSF

https://osf.io/jsxdq/

This includes PAPER, DATA, and (partial) RESULTS. The reason that only partial results are uploaded to OSF is the data size. We host the full results on Dropbox and do not have a better way for now (>150 GB).

**Comment by steveharoz** [comment]
Hi Daniel. Thanks for posting this. I have some suggestions that can improve your OSF repository:

1. For your paper, I recommend to go to http://osf.io/preprints, add a new preprint, and "connect preprint to existing OSF project". Then way your paper will be archived and be more discoverable.

![image](https://user-images.githubusercontent.com/2257540/48214697-cda10100-e380-11e8-96d1-7e4079999735.png)

2. The terminology is a bit confusing here, but the "Data" badge is for measurements/result. Everything needed to replicate the measurements/result is part of the "Materials" badge. I what you've called DATA is actually part of your materials, as it's datasets used for generating images. Is that right?

3. For your really large results, try https://dataverse.harvard.edu/ or https://datadryad.org/

**Comment by haehn** [comment]
Thanks, @steveharoz ! Dataverse is not usable yet imho (it only supports a flat hierarchy, no folders yadayada) - we tried it!

Data for me includes results and models! So we uploaded results and models to OSF.

**Comment by haehn** [comment]
preprint is online https://osf.io/8b9xs/

**Comment by steveharoz** [comment]
I haven't used Dataverse, so that that's frustrating to hear. Thanks for letting me know!

I'll update the site with the new info.
