### ISSUE TITLE
Some VIS papers

### ISSUE THREAD

**Issue by DuetPairComp** [steveharoz/open-access-vis#65]
We want to contribute to making VIS more openly accessible! Our papers at VIS are now on OSF.

MAQUI: Interweaving Queries and Pattern Mining for Recursive Event Sequence Exploration
[https://osf.io/zd6w2/](https://osf.io/zd6w2/)

Duet: Helping Data Analysis Novices Conduct Pairwise Comparisons by Minimal Specification
[https://osf.io/7gazn/](https://osf.io/7gazn/)

Segue: Overviewing Evolution Patterns of Egocentric Networks by Interactive Construction of Spatial Layouts
[https://osf.io/2p3fq/](https://osf.io/2p3fq/)

Terrance

**Comment by steveharoz** [comment]
Excellent! Thanks Terrance. I recommend one more step though. The github content isn't actually stored on OSF. To do so, you need to make a registration to snapshot the current state. For each project, go to Registration -> New Registration -> Open Ended -> then just write "final published state" or something similar.

**Comment by steveharoz** [comment]
Hi Terrance. The Duet project doesn't have a registration. I'll close the issue for now by using the github repository, but feel free to post a comment to this issue if that changes.
