### ISSUE TITLE
adding short paper from scivis 2018

### ISSUE THREAD

**Issue by DABH** [steveharoz/open-access-vis#69]
VRGE: An Immersive Visualization Application for the Geosciences
SciVis 2018 Short Papers: Visual Abstractions, Perceptual Study and Immersive Visualization session
PDF: http://dabh.io/papers/vrge.pdf
Thumbnail: attached

Thanks for maintaining this nice resource for the community!

![vrge4x3](https://user-images.githubusercontent.com/1920464/56939416-082c6080-6abd-11e9-9b48-558fd1c98af7.png)

**Comment by steveharoz** [comment]
Thank you for offering to contribute. Unfortunately, the site is only for content that has been made available by the conference.
