### ISSUE TITLE
The Effect of Proximity in Social Data Charts on Perceived Unity

### ISSUE THREAD

**Issue by promann** [steveharoz/open-access-vis#70]
To add a new paper URL:

1. Paper title: The Effect of Proximity in Social Data Charts on Perceived Group Unity
2. First author: Marlen Promann
3. Paper url:[https://www.dropbox.com/s/f0ii2okghq7ootd/Promann_Brunswicker_IEEEVAST_2018_Revision_FINAL2.pdf?dl=0](url)
4. Paper abstract: Social data charts – visual presentations of quantitative data about peer behaviors – may offer new means to motivate individuals to participate in group goals. However, to do so these charts need to create a semantic response of ‘unity’ among the chart viewers in order to overcome the problems of social loafing where people act selfishly and undervalue the group’s goal. In this paper, we focus on two properties of social data charts that may affect a viewer’s perceptions of unity: (1) The skewness in the data structure – the statistical distribution of the social data, and (2) the proximity in the visual structure of the chart – the spatial organization of the data points. We performed a controlled perceptual experiment to examine the effect of proximity and skewness on four different semantic facets of perceived group unity: similarity, entitativity, rapport, and centrality. We exposed 179 participants on Amazon Mechanical Turk to different group charts using a 2 x 2 factorial design, varying both proximity and skewness. Our two-way ANCOVA analyses reveal three important findings: (1) Across all conditions, proximity has a strong positive effect on perceived group unity and conveys a social meaning of group entitativity, as well as, member similarity and rapport; (2) Skewness and proximity interact in a non-linear way, suggesting that skewness creates a negative force that modifies the semantic responses to high proximity; and (3) The perceptual responses to proximity have different semantic facets that are either stable or sensitive to skewness. These findings contribute to perceptual as well as social InfoVis literature.
5. Supporting Document: [https://www.dropbox.com/s/tpkan6ohwhe39w5/Promann_Brunswicker_IEEEVAST_2018_SupportingDocument_FINAL.pdf?dl=0](url)
6. Url to the presentation: [https://vimeo.com/300463147](url)
7. Thumbnail (as a 400 x 300 png): [https://www.dropbox.com/s/0jiz7f8j450wuxx/Promann_IEEEVast_2018_Thumbnail.png?dl=0](url)

Thank you for the update and the awesome project!
Marlen

**Comment by steveharoz** [comment]
Thank you for offering to contribute. Unfortunately, the site is only for content that has been made available before the conference.

**Comment by promann** [comment]
Hi Steve,

Oh no, my bad for misunderstanding. I’m still learning to navigate the
opportunities landscape of academic publishing :)
I appreciate your reply. May I just ask, out of curiosity, if you only
compile this awesome page ahead of the conference, because after it will be
in the digital library (so, in essence, you are restricted by copyright),
is my understanding correct?
Thanks so much for the educational feedback!

Sincerely,
Marlen

Marlen Promann
marlen.promann@gmail.com
USA: +1 765 250 1630
Estonia: +372 5155 778
