### ISSUE TITLE
VIS 2019 paper updates

### ISSUE THREAD

**Issue by fredhohman** [steveharoz/open-access-vis#75]
These papers are already included, but I'm filling in some more details. Thanks (once again!) for the effort!

1. Title: TeleGam: Combining Visualization and Verbalization for Interpretable Machine Learning
AuthorPDF: https://fredhohman.com/papers/19-telegam-vis.pdf
Abstract: While machine learning (ML) continues to find success in solving previously-thought hard problems, interpreting and exploring ML models remains challenging. Recent work has shown that visualizations are a powerful tool to aid debugging, analyzing, and interpreting ML models. However, depending on the complexity of the model (e.g., number of features), interpreting these visualizations can be difficult and may require additional expertise. Alternatively, textual descriptions, or verbalizations, can be a simple, yet effective way to communicate or summarize key aspects about a model, such as the overall trend in a model’s predictions or comparisons between pairs of data instances. With the potential benefits of visualizations and verbalizations in mind, we explore how the two can be combined to aid ML interpretability. Specifically, we present a prototype system, TeleGam, that demonstrates how visualizations and verbalizations can collectively support interactive exploration of ML models, for example, generalized additive models (GAMs). We describe TeleGam’s interface and underlying heuristics to generate the verbalizations. We conclude by discussing how TeleGam can serve as a platform to conduct future studies for understanding user expectations and designing novel interfaces for interpretable ML.
ExplanationPage: https://poloclub.github.io/telegam/
SourceMaterials: https://github.com/poloclub/telegam
Thumbnail: 

![telegam_fred](https://user-images.githubusercontent.com/5741691/67333107-dd9feb00-f4d4-11e9-90f5-6023a3485fd9.png)

2. Summit: Scaling Deep Learning Interpretability by Visualizing Activation and Attribution Summarizations
DOI: 10.1109/TVCG.2019.2934659
ExplanationPage: http://fredhohman.com/summit
SourceMaterials: https://github.com/fredhohman/summit

3. FairVis: Visual Analytics for Discovering Intersectional Bias in Machine Learning
ExplanationPage: https://poloclub.github.io/FairVis/
SourceMaterials: https://github.com/poloclub/fairvis

4. ElectroLens: Understanding Atomistic Simulations through Spatially-resolved Visualization of High-dimensional Features
SourceMaterials: https://github.com/ray38/ElectroLens
Thumbnail: 

![electrolens_xiangyun](https://user-images.githubusercontent.com/5741691/67333557-9c5c0b00-f4d5-11e9-87f9-af315b57853d.png)

**Comment by steveharoz** [comment]
Thanks Fred! I'll try to add the explanation and code this evening. For the papers, the site only includes papers in persistent immutable repositories, including http://osf.io/preprints and http://arxiv.org

**Comment by fredhohman** [comment]
Got it. Papers 2-4 are all on arXiv already (the links are already included in the dataset too). For paper 1, here's the new OSF link: https://osf.io/p3wnm/ (DOI: 10.31219/osf.io/p3wnm).

Perhaps this should be a new issue, but when making a new issue the current template states an author's personal/academic website is acceptable for paper URLs, but sounds like that's changed. Just a heads up if others ask the same thing! 🙂

**Comment by steveharoz** [comment]
Thanks. Yeah, those instructions were out of date, but I've updated them. I added Telegam, the Summit URLs, and the explanation pages. For the other source code pages, oavis only links to URLs that appear in the paper. Feel free to reopen the issue if I missed anything.
