### ISSUE TITLE
Additional URL for InfoVIS shortpaper

### ISSUE THREAD

**Issue by davidpomerenke** [steveharoz/open-access-vis#77]
For Pomerenke, Dennig, Keim, Fuchs & Blumenschein, "Slope-Dependent Rendering of Parallel Coordinates to Reduce Density Distortion and Ghost Clusters", there is computational material (code and data used for visualizations) available https://osf.io/sy3dv/ – the URL is also in the paper.

**Comment by steveharoz** [comment]
fixed in 35b06646e60c1dbface96c7b0f01afc0303cebeb
